
source 'https://cdn.cocoapods.org'
source 'https://github.com/WZLYiOS/WZPodSpecs.git'

platform :ios,'11.0'
use_frameworks!

target 'WZTagStackView_Example' do
  pod 'WZTagStackView', :path => '../'
  
  target 'WZTagStackView_Tests' do
    inherit! :search_paths
    
  end
end
