
source 'https://cdn.cocoapods.org'


platform :ios,'10.0'
use_frameworks!

target 'WZTagStackView_Example' do
  pod 'WZTagStackView', :path => '../'
  
  target 'WZTagStackView_Tests' do
    inherit! :search_paths
    
  end
end
